name: test hello action
on:
  push:

jobs:
  build:
  name: Hello action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./action.yml
      with:
        NAME: "hirantha"